# name: Kubernetes Deploy
# on:
#     workflow_call:
# jobs:
#     deploy:
#         name: "Deploy"
#         runs-on: ubuntu-latest
#         steps:
#             -   name: Getting Code
#                 uses: actions/checkout@v4
#                 #Kubernetes Set Context
#             -   name: Context Settings
#                 uses: azure/k8s-set-context@v4
#                 with:
#                     method: kubeconfig
#                     kubeconfig: ${{ secrets.K8S_CONFIG }}
#             -   name: Kubernetes Deploy
#                 uses: Azure/k8s-deploy@v5
#                 with:
#                     manifests: |
#                         k8s/deployment.yaml
#                     images: |
#                         lmatrangolo/projeto-devops-pro:v${{ github.run_number }}
