
name: Pipeline CI/CD
run-name: Pipeline CI/CD executed from ${{ github.actor }} in ${{ github.run_number }}
on:
    workflow_dispatch:
    push:
        branches:
            -   main
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            -   name: Get Project Code
                uses: actions/checkout@v4
            -   name: Dotnet Setup
                uses: actions/setup-dotnet@v4
                with:
                    dotnet-version: "8.0.300"
            -   name: Command Build execution
                working-directory: ./src
                run: dotnet build Review-Filmes.sln
    tests:
        needs: [build]
        uses: LucasGit10/desafio-cicd-01/.github/workflows/teste.yml@main
        secrets: inherit
    release:
        name: Release Creation
        runs-on: ubuntu-latest
        needs: [tests]
        steps:
            -   name: Get Project Code
                uses: actions/checkout@v4
            -   name: DockerFile Analisys
                uses: hadolint/hadolint-action@v3.1.0
                with:
                    dockerfile: ./src/Review-Filmes.Web/Dockerfile
            -   name: Docker Hub Login
                uses: docker/login-action@v3
                with:
                    username: ${{ secrets.DOCKERHUB_USER }}
                    password: ${{ secrets.DOCKERHUB_PWD}}
            -   name: Image-Build and Push
                uses: docker/build-push-action@v6
                with:
                    push: true
                    context: ./src
                    file: ./src/Review-Filmes.Web/Dockerfile
                    tags: |
                        lmatrangolo/projeto-devops-pro:latest
                        lmatrangolo/projeto-devops-pro:v${{ github.run_number }}
            -   name: Trivy Execution
                uses: aquasecurity/trivy-action@0.23.0
                with:
                    scan-type: 'image'
                    image-ref: lmatrangolo/projeto-devops-pro:v${{ github.run_number }}
                    format: sarif
                    output: trivy-docker-result.sarif
                    severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
            -   name: File Trivy Upload to Github
                uses: github/codeql-action/upload-sarif@v3
                with:
                    category: docker-result
                    sarif_file: trivy-docker-result.sarif
    # deploy-homolog:
    #     needs: [release]
    #     uses: LucasGit10/desafio-cicd-01/.github/workflows/deploy.yml@main
    #     secrets: inherit