name: Tests Executions
on:
    workflow_call:
jobs:
    unity-test:
        name: Unity Tests
        runs-on: ubuntu-latest
        steps:
            -   name: Get Project Code
                uses: actions/checkout@v4
            -   name: Dotnet Setup
                uses: actions/setup-dotnet@v4
                with:
                    dotnet-version: "8.0.300"
            -   name: Unity Test Execution
                working-directory: ./src
                run: dotnet test ./Review-Filmes.Test.Unit/Review-Filmes.Test.Unit.csproj
    integration-test:
        name: Integration Test
        runs-on: ubuntu-latest
        services:
            postgre:
                image: postgre:latest 
                ports:
                    -   5432:5432
                env:
                    POSTGRES_USER: review
                    POSTGRES_PASSWORD: postgrespwd
                    POSTGRES_DB: review-filmes
        steps:
            -   name: Get Project Code
                uses: actions/checkout@v4
            -   name: Dotnet Setup
                uses: actions/setup-dotnet@v4
                with:
                    dotnet-version: "8.0.300"
            -   name: Integration Test Execution
                working-directory: ./src
                run: dotnet test ./Review-Filmes.Test.Integration/Review-Filmes.Test.Integration.csproj
                env:
                    ConnectionStrings__DefaultConnection: "Host=localhost;Port=5432;Database=review-filmes;Username=review;Password=postgrespwd"
                