name: Tests Executions
on:
    workflow_call:
jobs:
    unity-test:
        name: Unity Tests
        runs-on: ubuntu-latest
        steps:
            -   name: Get Project Code
                uses: actions/checkout@v4
            -   name: Dotnet Setup
                uses: actions/setup-dotnet@v4
                with:
                    dotnet-version: "8.0.300"
            -   name: Unity Test Execution
                working-directory: ./src
                run: dotnet test ./Review-Filmes.Test.Unit/Review-Filmes.Test.Unit.csproj
